# Generated by Django 5.2.3 on 2025-08-07 17:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TallyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(max_length=50)),
                ('voucher_number', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('remaining_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Remaining unpaid amount for sales, or unallocated amount for receipts', max_digits=15, null=True)),
                ('party_name', models.CharField(max_length=255)),
                ('register_type', models.CharField(choices=[('sales', 'Sales'), ('receipt', 'Receipt'), ('payment', 'Payment')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reconciled', models.BooleanField(default=False, help_text='Whether this transaction has been fully matched/allocated')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_debit', models.BooleanField()),
                ('is_credit', models.BooleanField()),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='transactions.tallytransaction')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_amount', models.DecimalField(decimal_places=2, help_text='Amount allocated from source to target', max_digits=15)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('delay_days', models.IntegerField(help_text='Number of days between source and target dates')),
                ('source_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_matches', to='transactions.tallytransaction')),
                ('target_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_matches', to='transactions.tallytransaction')),
            ],
        ),
        migrations.AddField(
            model_name='tallytransaction',
            name='related_transactions',
            field=models.ManyToManyField(help_text='For sales: linked receipts; for receipts: linked sales', related_name='linked_transactions', through='transactions.TransactionMatching', to='transactions.tallytransaction'),
        ),
        migrations.CreateModel(
            name='BankBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(default='default', max_length=255)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'account_name'], name='transaction_company_ff5799_idx')],
                'unique_together': {('company', 'account_name')},
            },
        ),
        migrations.CreateModel(
            name='FixedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_std_deviation', models.DecimalField(decimal_places=2, default=0, help_text='Standard deviation of historical payment amounts', max_digits=15)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('interval_days', models.IntegerField(default=30, help_text='Average interval between payments in days')),
                ('interval_std_deviation', models.FloatField(default=0.0, help_text='Standard deviation of payment intervals in days')),
                ('pattern_consistency', models.FloatField(default=1.0, help_text='Score indicating how consistent the expense pattern is', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('due_day', models.IntegerField(help_text='Day of the month when payment is due', validators=[django.core.validators.MinValueValidator(1)])),
                ('next_date', models.DateField()),
                ('last_paid_date', models.DateField(blank=True, help_text='Date when this expense was last paid', null=True)),
                ('sample_size', models.IntegerField(default=0, help_text='Number of transactions used to identify this pattern')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'next_date'], name='transaction_company_ab1dc3_idx'), models.Index(fields=['is_active'], name='transaction_is_acti_e3142b_idx'), models.Index(fields=['pattern_consistency'], name='transaction_pattern_e067ce_idx')],
            },
        ),
        migrations.CreateModel(
            name='LedgerMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('type', models.CharField(choices=[('debtor', 'Debtor'), ('creditor', 'Creditor'), ('bank', 'Bank'), ('cash', 'Cash'), ('other', 'Other')], max_length=50)),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'name'], name='transaction_company_fb175b_idx'), models.Index(fields=['company', 'type'], name='transaction_company_da5d7b_idx')],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PartyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=255)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('expected_payment_date', models.DateField(blank=True, null=True)),
                ('payment_probability', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'party_name'], name='transaction_company_021471_idx'), models.Index(fields=['expected_payment_date'], name='transaction_expecte_3c0246_idx')],
                'unique_together': {('company', 'party_name')},
            },
        ),
        migrations.CreateModel(
            name='PaymentPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=255)),
                ('avg_payment_days', models.IntegerField(default=30)),
                ('confidence_score', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('delay_std_deviation', models.FloatField(default=0.0, help_text='Standard deviation of payment delays in days', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('pattern_consistency', models.FloatField(default=1.0, help_text='Score indicating how consistent the payment pattern is', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('sample_size', models.IntegerField(default=0, help_text='Number of transactions used to calculate the pattern')),
                ('expected_payment_date', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_analysis_date', models.DateField(auto_now=True, help_text='Date when the pattern was last analyzed')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'party_name'], name='transaction_company_1b80cb_idx'), models.Index(fields=['expected_payment_date'], name='transaction_expecte_ccb327_idx'), models.Index(fields=['pattern_consistency'], name='transaction_pattern_b047b4_idx')],
                'unique_together': {('company', 'party_name')},
            },
        ),
        migrations.AddIndex(
            model_name='transactionmatching',
            index=models.Index(fields=['source_transaction'], name='transaction_source__be8609_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionmatching',
            index=models.Index(fields=['target_transaction'], name='transaction_target__71f96c_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionmatching',
            index=models.Index(fields=['matched_at'], name='transaction_matched_c908a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transactionmatching',
            unique_together={('source_transaction', 'target_transaction')},
        ),
        migrations.AddIndex(
            model_name='tallytransaction',
            index=models.Index(fields=['company', 'party_name'], name='transaction_company_b257cb_idx'),
        ),
        migrations.AddIndex(
            model_name='tallytransaction',
            index=models.Index(fields=['date'], name='transaction_date_6c705e_idx'),
        ),
        migrations.AddIndex(
            model_name='tallytransaction',
            index=models.Index(fields=['register_type'], name='transaction_registe_8f41b5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tallytransaction',
            unique_together={('company', 'voucher_type', 'voucher_number')},
        ),
    ]
