# Generated by Django 5.2.3 on 2025-08-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partybalance',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tallytransaction',
            name='register_type',
            field=models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('receipt', 'Receipt'), ('payment', 'Payment'), ('journal', 'Journal'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note'), ('stock_journal', 'Stock Journal'), ('physical_stock', 'Physical Stock'), ('manufacturing_journal', 'Manufacturing Journal'), ('contra', 'Contra'), ('payroll', 'Payroll'), ('opening_balance', 'Opening Balance'), ('bank_allocation', 'Bank Allocation'), ('purchase_order', 'Purchase Order'), ('sales_order', 'Sales Order')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='tallytransaction',
            index=models.Index(fields=['company', 'is_reconciled'], name='transaction_company_7bc8d9_idx'),
        ),
    ]
