# Generated by Django 4.2.6 on 2025-09-07 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_partybalance_current_balance_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tallytransaction',
            name='transaction_company_7bc8d9_idx',
        ),
    ]
