# Generated by Django 5.2.3 on 2025-09-02 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawTallyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(max_length=100)),
                ('voucher_number', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('remaining_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('party_name', models.CharField(blank=True, max_length=255)),
                ('register_type', models.CharField(blank=True, max_length=50)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False, help_text='Whether this raw row has been normalized into transactions.TallyTransaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'voucher_type'], name='accounts_ra_company_e74bdc_idx'), models.Index(fields=['company', 'party_name'], name='accounts_ra_company_c27c6b_idx'), models.Index(fields=['processed'], name='accounts_ra_process_cbdbcc_idx')],
            },
        ),
    ]
